# Generated by Django 3.2.4 on 2021-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True),
        ),
    ]
