# Generated by Django 3.2.4 on 2021-10-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
